PUT http://localhost:3003/api/blogs/68b98e96cb24346fb305114b HTTP/1.1
Content-Type: application/json

{
    "title": "a note created by playwright",
    "author": "playwright",
    "url": "work.com",
    "url": "playwright.com",
    "comments": ["hello", "goodbye"]
}


    
    